# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mainwindow(object):
    def setupUi(self, Mainwindow):
        Mainwindow.setObjectName("Mainwindow")
        Mainwindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        Mainwindow.setFont(font)
        self.Label_Status = QtWidgets.QLabel(Mainwindow)
        self.Label_Status.setGeometry(QtCore.QRect(210, 380, 401, 61))
        self.Label_Status.setTextFormat(QtCore.Qt.AutoText)
        self.Label_Status.setObjectName("Label_Status")
        self.spinBox_S2M_start_port = QtWidgets.QSpinBox(Mainwindow)
        self.spinBox_S2M_start_port.setGeometry(QtCore.QRect(30, 171, 379, 25))
        self.spinBox_S2M_start_port.setObjectName("spinBox_S2M_start_port")
        self.comboBox_port_order = QtWidgets.QComboBox(Mainwindow)
        self.comboBox_port_order.setGeometry(QtCore.QRect(30, 227, 379, 25))
        self.comboBox_port_order.setObjectName("comboBox_port_order")
        self.comboBox_port_order.addItem("")
        self.comboBox_port_order.addItem("")
        self.label_2 = QtWidgets.QLabel(Mainwindow)
        self.label_2.setGeometry(QtCore.QRect(30, 146, 379, 19))
        self.label_2.setObjectName("label_2")
        self.pushButton_S2Mixed = QtWidgets.QPushButton(Mainwindow)
        self.pushButton_S2Mixed.setGeometry(QtCore.QRect(30, 113, 379, 27))
        self.pushButton_S2Mixed.setAutoDefault(False)
        self.pushButton_S2Mixed.setFlat(False)
        self.pushButton_S2Mixed.setObjectName("pushButton_S2Mixed")
        self.label_3 = QtWidgets.QLabel(Mainwindow)
        self.label_3.setGeometry(QtCore.QRect(30, 202, 379, 19))
        self.label_3.setObjectName("label_3")
        self.Label_Show_Opened_File = QtWidgets.QLabel(Mainwindow)
        self.Label_Show_Opened_File.setGeometry(QtCore.QRect(30, 30, 751, 19))
        self.Label_Show_Opened_File.setScaledContents(True)
        self.Label_Show_Opened_File.setObjectName("Label_Show_Opened_File")
        self.pushButton_Read_SnP = QtWidgets.QPushButton(Mainwindow)
        self.pushButton_Read_SnP.setGeometry(QtCore.QRect(30, 55, 379, 27))
        self.pushButton_Read_SnP.setAutoDefault(False)
        self.pushButton_Read_SnP.setFlat(False)
        self.pushButton_Read_SnP.setObjectName("pushButton_Read_SnP")
        self.label = QtWidgets.QLabel(Mainwindow)
        self.label.setGeometry(QtCore.QRect(30, 88, 379, 19))
        self.label.setObjectName("label")

        self.retranslateUi(Mainwindow)
        self.comboBox_port_order.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Mainwindow)

    def retranslateUi(self, Mainwindow):
        _translate = QtCore.QCoreApplication.translate
        Mainwindow.setWindowTitle(_translate("Mainwindow", "SnP Reader"))
        self.Label_Status.setText(_translate("Mainwindow", "Status : "))
        self.comboBox_port_order.setCurrentText(_translate("Mainwindow", "even odd"))
        self.comboBox_port_order.setItemText(0, _translate("Mainwindow", "even odd"))
        self.comboBox_port_order.setItemText(1, _translate("Mainwindow", "sequential"))
        self.label_2.setText(_translate("Mainwindow", "The first port of your mixed mode network"))
        self.pushButton_S2Mixed.setText(_translate("Mainwindow", "Convert"))
        self.label_3.setText(_translate("Mainwindow", "Choose the order of ports"))
        self.Label_Show_Opened_File.setText(_translate("Mainwindow", "Current File : None"))
        self.pushButton_Read_SnP.setText(_translate("Mainwindow", "Choose a SnP File"))
        self.label.setText(_translate("Mainwindow", "Convert S-par. to mixed mode S-par."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mainwindow = QtWidgets.QWidget()
    ui = Ui_Mainwindow()
    ui.setupUi(Mainwindow)
    Mainwindow.show()
    sys.exit(app.exec_())
